version: 0.2

env:
  parameter-store:
    AMBITZ_SECRET: "/traceqr_ja/backend/sample/secret"
    DATABASE_URL: "/traceqr_ja/backend/sample/db_url"
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - n 18.5
      - npm install -g yarn
      - yarn
      - yarn lint:report
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo $AWS_DEFAULT_REGION
      - AWS_ACCOUNT_ID=700515655651
      - ECR_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      - REPOSITORY_URI=${ECR_URI}/express_sample
      - CONTAINER_NAME=express_sample
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_URI

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo $AMBITZ_SECRET
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
reports:
  unittest-rep-group:
    files:
      - '**/*'
    base-directory: reports/