version: '3'
services:
  backend:
    container_name: backend
    build:
      context: .
      target: runtime-stage
    command: npm start
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
    networks:
      - backend
  postgres:
    image: "postgres:14"
    container_name: "postgres"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
      PGPASSWORD: test
      POSTGRES_DB: test
      TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend
volumes:
  postgres:

networks:
  backend: